import Head from 'next/head'
import { Heebo } from 'next/font/google'
import Navbar from '@/components/Navbar'
import { createContext, useState } from 'react'

const heebo = Heebo({
  weight: ["400", "600"],
  subsets: ["latin"]
})

export const DarkContext = createContext();

export default function Home() {

  const [dark, setDark] = useState("");
  
  return (
    <>
      <Head>
        <title>Rattlehead's Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DarkContext.Provider value={setDark}>
        <main className={`${heebo.className} h-screen ${dark}`}>
          <div className="h-screen dark:bg-black dark:text-white transition-colors">
            <Navbar />
            <h1>Hello world</h1>
          </div>
        </main>
      </DarkContext.Provider>
    </>
  );
}
