import Head from "next/head";
import { getSortedPostsData } from "@/lib/posts";
import Layout from "@/components/Layout";


export async function getStaticProps() {
  const allPostsData = getSortedPostsData();

  return {
    props: {
      allPostsData,
    },
  };
}

export default function Home({ allPostsData }) {

  return (
    <>
      <Head>
        <title>Rattlehead's Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <ul className="sm:grid sm:grid-cols-2 flex flex-col gap-4 items-center">
          {allPostsData.map(({ id, title, date }) => (
            <li key={id} className="rounded-md flex p-2 flex-col w-80">
              <h2 className="font-bold ">{title}</h2>

              <div className="text-sm italic">{id}</div>

              <div className="text-sm">{date}</div>
            </li>
          ))}
        </ul>
      </Layout>
    </>
  );
}
